version: 3.8
  services:
    app:
      build:.
      volume: .:/app
      restart: always
      ports:
        - "8000:8000"


    db:
      image: postgrey-alpine
      volume: data_base:/var/lib/postgresql/data
      restart: unless-stopped
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 30s 
        timeout: 5s
        retries: 5

      conditions:
        - service_healthy: db