# Generated by Django 5.2.6 on 2026-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encrypted_master_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='master_key_iv',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='master_key_salt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
