# Generated by Django 5.2.6 on 2026-01-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_customuser_encrypted_master_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='master_key_iv',
            new_name='fixed_key_hex',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='encrypted_master_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='master_key_salt',
        ),
    ]
