# Generated by Django 5.2.6 on 2026-02-01 06:40

import django.contrib.auth.models
import django.db.models.deletion
import passwords.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_rename_master_key_iv_customuser_fixed_key_hex_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='credential',
            name='passwords_c_vault_i_a1818c_idx',
        ),
        migrations.RemoveIndex(
            model_name='credential',
            name='passwords_c_vault_i_c14800_idx',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='auth_tag',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fixed_key_hex',
        ),
        migrations.AddField(
            model_name='credential',
            name='tag',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salt',
            field=models.BinaryField(default=passwords.models.generate_salt),
        ),
        migrations.AddField(
            model_name='vault',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='vault_key_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='iv',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='credential',
            name='secret_encrypted',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='auth_tag',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='iv',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='secret_encrypted',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='vault',
            name='kdf_params',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
