# Generated by Django 5.2.6 on 2026-02-01 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0005_credential_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
